[tool.pylint.MESSAGE_CONTROL]
disable = """
    line-too-long,
    abstract-method,
    no-member,
    import-error,
    missing-module-docstring,
    missing-function-docstring,
    missing-class-docstring,
    missing-class-docstring,
    too-few-public-methods,
    fixme,
    duplicate-code,
    no-self-use

"""
enable = "useless-suppression"

[tool.pylint.REPORTS]
reports = "no"

[tool.pylint.FORMAT]
max-line-length = "120"

[tool.pylint.BASIC]
good-names = "_,i,e,set_up,tear_down,max_diff"

[tool.mypy]
python_version = 3.9
pretty = true
show_traceback = false
color_output = true
allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = false
disallow_incomplete_defs = true
ignore_missing_imports = true
implicit_reexport = true
no_implicit_optional = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_no_return = false
warn_redundant_casts = true
warn_return_any = false
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.black]
line-length = 120
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 39
line_length = 120
known_typing = ["typing", "types", "typing_extensions", "mypy", "mypy_extensions"]
known_third_party = ["aioredis", "elasticsearch", "fastapi", "orjson", "pydantic", "uvicorn", "uvloop"]
known_first_party = ["api", "core", "db", "models", "services"]
sections = ["FUTURE", "TYPING", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
include_trailing_comma = true
indent = 4
color_output = true

