# services
ES_HOST = "0.0.0.0:9200"
REDIS_HOST = ""

# es indexes
MOVIES_INDEX_NAME = "movies"
GENRES_INDEX_NAME = "genre"
FILMS_POSTFIX = "films/"
GENRES_POSTFIX = "genres/"
PERSONS_POSTFIX = "persons/"

# API
API_SERVICE_URL = "http://127.0.0.1:8000"

# API V1
API_V1_PREFIX = "/api/v1/"
FILMS_V1_URL = API_SERVICE_URL + API_V1_PREFIX + FILMS_POSTFIX
PERSONS_V1_URL = API_SERVICE_URL + API_V1_PREFIX + PERSONS_POSTFIX
GENRES_V1_URL = API_SERVICE_URL + API_V1_PREFIX + GENRES_POSTFIX

